config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'listings#index'

  resources :listings do
  	collection do
  		get 'search'
  	end
  	resources :reviews, except: [:index,:show]
  end



  get '/about', to: 'pages#about'
  get '/common', to: 'pages#common'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	has_many :reviews

	 has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  searchkick
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_file_name, presence: true
  validates :product_no, presence: true

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except:[:index, :show]
  


  def search
    if params[:search].present?
      @listings = Listing.search(params[:search])
    else
      @listings = Listing.all
    end
  end


  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all

    #ロボット作品一覧コード
    
    @rand_num = rand(1..1000)
    @rand_price = rand(1..300)
    @set_number = rand(1..4)
    @bg = rand(1..2)

    #ロボットの種類を決める条件式
    if @set_number == 1
      @set = "set1"
    elsif 
      @set_number = 2
       @set = "set2"
    elsif 
      @set_number = 3
       @set = "set3"
    else
       @set = "set4"
    end


    #背景を決める条件式
      if @bg == 1
        @backgroud = "bg1"
      else
        @backgroud = "bg2"
      end

    @robots = Faker::Avatar.image(@rand_num, "300x300", "png", @set, @backgroud)

    @rand_num = rand(1..1000)
    @rand_price = rand(1..300)
    @set_number = rand(1..4)
    @bg = rand(1..2)

    #ロボットの種類を決める条件式
    if @set_number == 1
      @set = "set1"
    elsif 
      @set_number = 2
       @set = "set2"
    elsif 
      @set_number = 3
       @set = "set3"
    else
       @set = "set4"
    end


    #背景を決める条件式
      if @bg == 1
        @backgroud = "bg1"
      else
        @backgroud = "bg2"
      end
    @robots2 = Faker::Avatar.image(@rand_num, "300x300", "png", @set, @backgroud)

    @rand_num = rand(1..1000)
    @rand_price = rand(1..300)
    @set_number = rand(1..4)
    @bg = rand(1..2)

    #ロボットの種類を決める条件式
    if @set_number == 1
      @set = "set1"
    elsif 
      @set_number = 2
       @set = "set2"
    elsif 
      @set_number = 3
       @set = "set3"
    else
       @set = "set4"
    end


    #背景を決める条件式
      if @bg == 1
        @backgroud = "bg1"
      else
        @backgroud = "bg2"
      end
    @robots3 = Faker::Avatar.image(@rand_num, "300x300", "png", @set, @backgroud)

    @rand_num = rand(1..1000)
    @rand_price = rand(1..300)
    @set_number = rand(1..4)
    @bg = rand(1..2)

    #ロボットの種類を決める条件式
    if @set_number == 1
      @set = "set1"
    elsif 
      @set_number = 2
       @set = "set2"
    elsif 
      @set_number = 3
       @set = "set3"
    else
       @set = "set4"
    end


    #背景を決める条件式
      if @bg == 1
        @backgroud = "bg1"
      else
        @backgroud = "bg2"
      end
    @robots4 = Faker::Avatar.image(@rand_num, "300x300", "png", @set, @backgroud)
  end

  
  def show
    @review = Review.where(listing_id: @listing.id)
    if @review.blank?
      @avg_review = 0
    else
      @avg_review = @review.average(:rating).round(2)
    end
  end

  
  def new
    @listing = current_user.listings.build
  end

   
  def edit
  end
 
  def create
    @listing = current_user.listings.build(listing_params)
    if @listing.save
      redirect_to @listing
    else
      render 'new'
    end
    
    

    # respond_to do |format|
    #   if @listing.save
    #     format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
    #     format.json { render :show, status: :created, location: @listing }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @listing.errors, status: :unprocessable_entity }
    #   end
    # end
  end
 
  def update


    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

   

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :power, :product_no, :price, :image)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing , html: { multipart: true } do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
       <div class="alert alert-danger">
         <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>
      </div>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :ロボットの名前 %>
    <%= form.text_field :name, id: :listing_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :ロボットの詳細 %>
    <%= form.text_area :description, id: :listing_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :ロボットの特技 %>
    <%= form.text_field :power, id: :listing_power, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :製造番号 %>
    <%= form.text_field :product_no, id: :listing_product_no, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :価格 %>
    <%= form.text_field :price, id: :listing_price, class: "form-control" %>
  </div>

    <div class="form-group">
    <%= form.label :画像添付 %>
    <%= form.file_field :image, id: :listing_image %>
  </div>

  <div class="actions">
    <%= form.submit 'ロボット記事投稿',class:"btn btn-info" %>
  </div>
<% end %>
<br> 

app/views/listings/edit.html.erb
<h1>ロボットの詳細変更</h1>

<%= render 'form', listing: @listing %>

<%= link_to '詳細', @listing,class:"btn btn-success"  %> |
<%= link_to '戻る', listings_path,class:"btn btn-warning"  %>

<div style="margin-bottom: 150px;"></div>

app/views/listings/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Robot Worldへようこそ</h1>
    <p>あなたが作製したロボットを投稿してみませんか？<br></p>
    <p>世界の開発者が新しいロボットを作り販売もしています。</p>
    <p><%= link_to "新規登録", new_user_registration_path ,class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>


  <div class="new_robots">
    <h2>最近投稿されたロボットです。</h2>
    <h3>カスタマービューを確認してみませんか？</h3>
   <br>
    <div class="row row-eq-height">
      <% @listings.each do |listing| %>
        <div class="col-sm-6 col-md-3">
          <div class="thumbnail index_thumb">
            <%= link_to (image_tag listing.image.url(:medium), class:"image"), listing  %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
 
 <br>
<hr>
<br>
<section class="text-center">
      <div class="container">
        
        <div class="row">
          <h2 style="text-align: center; color:white;">世界の開発者から声が届いています。</h2>
          <div class="col-sm-12 col-md-4 professor_profile">
            <div class="professor_jpeg">               
               <%= link_to image_tag('/assets/professor_01.jpeg',  class: 'img-circle'),  common_path %>
              <!-- <img class="img-circle" src="/assets/pic1.jpeg" alt=""> -->
              <h4>クリストファーE 工学博士.</h4>
              <p class="font-weight-light mb-0">"世界の技術者を集め販売されている最新型の感情認識ヒューマノイドロボットです。"</p> <%= link_to "詳細を見る", common_path, class: "btn btn-success" %>
            </div>
          </div>

          <div class="col-sm-12 col-md-4 professor_profile" >
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <%= link_to image_tag('/assets/professor_02.jpeg',  class: 'img-circle'),  common_path %>
              <!-- <img class="img-circle" src="/assets/professor_02.jpeg" alt=""> -->
              <h4>ジェシカ S 教授.</h4>
              <p class="font-weight-light mb-0">"ペンシルベニア工学大学で最新版のロボットを作製しました。世界中の人を見分ける能力を身につけています。"</p>
              <%= link_to "詳細を見る", common_path, class: "btn btn-success" %>
            </div>
          </div>

          <div class="col-sm-12 col-md-4 professor_profile">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <%= link_to image_tag('/assets/professor_03.jpeg',  class: 'img-circle'),  common_path %>
              <!-- <img class="img-circle" src="" alt=""> -->
              <h4>デイビッド W 准教授.</h4>
              <p class="font-weight-light mb-0">"パトレシアス国立大学の学生により<br>発明されたロボットです。"</p>
              <%= link_to "詳細を見る", common_path, class: "btn btn-success" %>
            </div>
          </div>
        </div>
      </div>
    </section>

<br>
<hr>
<br>
<div class="robot_introduction">
<h2>最新ロボットのご紹介</h2>
<br>


<div class="row">
 
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img src="<%= @robots %> ">
     </div>
  </div>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img src="<%= @robots2 %>">
     </div>
  </div>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img src="<%= @robots3 %>">
     </div>
  </div>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img src="<%= @robots4 %>">
     </div>
  </div>
</div>
</div>
 
<br><br><br>

app/views/listings/new.html.erb
<h1>あなたのロボットを投稿</h1>

<%= render 'form', listing: @listing %>
<br>
<%= link_to '一覧記事に戻る', listings_path, class: "btn btn-warning" %>

<div style="margin-bottom: 250px;"></div>
  
 

app/views/listings/search.html.erb
<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag listing.image.url(:medium), class:"image"), listing  %>
      </div>
    </div>

  <% end %>
</div>

<div style="margin-bottom: 250px;"></div>

app/views/listings/show.html.erb
<div class="panal panal-defaul" style="background-color: white;">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @listing.image.url(:medium) %><br><br>
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@review.length} reviews" %></em>

        <div class="table-responsive">
          <table class="table">
            <tr>
              <td>名前:</td>
              <td><%= @listing.name %></td>
            </tr>
            <tr>
              <td>詳細:</td>
              <td><%= @listing.description %></td>
            </tr>
            <tr>
              <td>特殊能力:</td>
              <td><%= @listing.power %></td>
            </tr>
            <tr>
              <td>製造番号:</td>
              <td><%= @listing.product_no %></td>
            </tr>
            <tr>
              <td>価格:</td>
              <td><%= @listing.price %> 万円</td>
            </tr>
          </table>
          <%= link_to "カスタマーレビューを書く" , new_listing_review_path(@listing), class: "btn btn-primary" %><br><br>
          <%= link_to '編集', edit_listing_path(@listing),class:"btn btn-text" %> |
          <%= link_to '一覧に戻る', listings_path,class:"btn btn-text" %>
        </div>
      </div>
      <!-- ここからshowの右画面 -->
      <div class="col-md-7 col-md-offset-1">
          <h1 class="reviews_head"><%= @listing.name %></h1>
          <p><%= @listing.description %></p>
          <br>

          <% if @review.blank? %>
            <h3>まだレビューがありません。</h3>
            <p>ぜひあなたの経験を投稿してみませんか？</p>
          <% else %>
            <% @review.each do |review| %>
              <div class="reviews">
                <div class="star-rating" data-score=  <%= review.rating %> ></div>
                <!-- <p><%= review.rating %></p> -->

                <p><%= review.comment %></p>
              </div>
            <% end %>
          <% end %>

      </div>
    </div>
  </div>
</div>
<br><br>
 

<!-- 
下記のサイトから持ってきた
https://stackoverflow.com/questions/35167149/im-using-raty-js-star-rating-system-how-do-i-show-the-equivalent-integer-value
star-ratingの部分を変更した
 -->
<div style="margin-bottom: 70px;"></div>

<script>
    $('.star-rating').raty({
        readOnly: true,
        path: '/assets/',
        score: function() {
            return $(this).attr('data-score')
        }
    });
</script>
 