config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'listings#index'

  resources :listings do
  	collection do
  		get 'search'
  	end
  	resources :reviews, except: [:index,:show]
  end



  get '/about', to: 'pages#about'
  get '/common', to: 'pages#common'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Robot World" , root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          
          <li><%= link_to '<i class="glyphicon glyphicon-pencil"></i> ロボット投稿'.html_safe,  new_listing_path, class: 'btn btn-default' %></li>
          <li><%= link_to "マイアカウント", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録",new_user_registration_path %></li>
          <li><%= link_to "ログイン",new_user_session_path %></li>
        <% end %>
      </ul>
        <%= form_tag search_listings_path, method: :get, class: "navbar-form navbar-right" ,role: "search" do %>
         <p><%= text_field_tag :search , params[:search], class: "form-control" %>
            <%= submit_tag "ロボット検索", name: nil, class: "btn btn-default" %>
        </p>
       <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Robot World</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    

      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">×</a> <!-- アラートダイアログに×ボタンをつける -->
          <%= msg %>
        </div>
      <% end %>
      

      

     
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>